/** Store-native appointments. Two steps, server truth, private management. */
(function(root){
  'use strict';
  function contactError(data){
    if(String(data.clientName||'').trim().length<2)return ['qb_name','Escribe tu nombre completo.'];
    if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(data.clientEmail||'').trim()))return ['qb_email','Escribe un correo electrónico válido.'];
    if(!/^\+[1-9][0-9]{7,14}$/.test(String(data.clientPhone||'').replace(/[\s().-]/g,'')))return ['qb_phone','Incluye el código de país en tu teléfono (ej. +52).'];
    return null;
  }
  class BookingState {
    constructor(){this.step=1;this.busy=false;this.appointment=null;this.signature='';this.requestKey='';this.managementToken='';}
    begin(payload,random){if(this.busy)return null;const signature=JSON.stringify(payload);if(signature!==this.signature){this.requestKey=random();this.signature=signature;}if(!this.managementToken)this.managementToken=random();this.busy=true;return Object.assign({},payload,{requestKey:this.requestKey,managementToken:this.managementToken});}
    finish(appointment){this.busy=false;if(appointment){this.appointment=appointment;this.step=3;}}
    resetRequest(){this.signature='';this.requestKey='';this.managementToken='';this.appointment=null;this.step=1;}
  }
  if(typeof module==='object'&&module.exports){module.exports={BookingState,contactError};return;}
  const formats={IN_PERSON:'Presencial',PHONE:'Llamada telefónica',GOOGLE_MEET:'Videollamada',WHATSAPP:'Llamada por WhatsApp'};
  class QuantixBookingUI {
    constructor(storefront){this.storefront=storefront;this.state=new BookingState();this.settings=null;this.selectedSlot='';this.loadVersion=0;this.rescheduling=false;this.context={};this.inertBefore=[];}
    el(id){return document.getElementById(id);}
    text(id,value){this.el(id).textContent=value==null?'':String(value);}
    show(id,visible){this.el(id).hidden=!visible;}
    available(){const t=this.storefront.tenant||root.QX_TENANT||{};return Boolean(t.emisorId&&t.featureMatrix&&t.featureMatrix.royal_agenda&&t.featureMatrix.royal_agenda.enabled);}
    async init(){
      ['qx_btn_nav_agenda','qx_dock_agenda'].forEach(id=>{const e=this.el(id);if(e)e.addEventListener('click',event=>{event.preventDefault();this.openAgendaModal();});});
      this.el('qx_agenda_close').addEventListener('click',()=>this.closeAgendaModal());this.el('qx_agenda_backdrop').addEventListener('click',()=>this.closeAgendaModal());
      this.el('qb_next').addEventListener('click',()=>this.next());this.el('qb_back').addEventListener('click',()=>{if(this.rescheduling){this.rescheduling=false;this.receipt(this.state.appointment);}else this.step(1);});
      this.el('qb_details').addEventListener('submit',e=>{e.preventDefault();this.next();});
      this.el('qb_date').addEventListener('change',()=>{this.selectedSlot='';this.loadSlots();});this.el('qb_requested_time').addEventListener('input',()=>{this.selectedSlot=this.el('qb_requested_time').value;this.summary();});
      this.el('qb_format').addEventListener('change',()=>this.summary());
      this.el('qb_slots').addEventListener('click',e=>{const b=e.target.closest('[data-time]');if(!b||b.disabled)return;this.selectedSlot=b.dataset.time;this.el('qb_slots').querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));this.summary();});
      ['qb_name','qb_email','qb_phone'].forEach(id=>this.el(id).addEventListener('input',()=>this.el(id).removeAttribute('aria-invalid')));
      this.el('qb_new').addEventListener('click',()=>{this.state.resetRequest();this.privateCode='';this.selectedSlot='';this.rescheduling=false;this.step(1);this.loadConfiguration();});
      this.el('qb_copy_link').addEventListener('click',()=>this.copyLink());this.el('qb_calendar').addEventListener('click',()=>this.calendar());this.el('qb_refresh').addEventListener('click',()=>this.refresh());
      this.el('qb_reschedule').addEventListener('click',()=>this.startReschedule());this.el('qb_cancel').addEventListener('click',()=>this.show('qb_cancel_confirm',true));this.el('qb_cancel_no').addEventListener('click',()=>this.show('qb_cancel_confirm',false));this.el('qb_cancel_yes').addEventListener('click',()=>this.privateAction('cancel'));
      this.el('qx_agenda_modal').addEventListener('keydown',e=>{if(e.key==='Escape'){e.stopPropagation();this.closeAgendaModal();}if(e.key==='Tab'){const items=Array.from(this.el('qx_agenda_modal').querySelectorAll('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href]')).filter(x=>x.offsetParent!==null);if(!items.length)return;const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
      const link=new URLSearchParams(root.location.hash.slice(1));
      if(link.has('appointment')&&link.has('key')){this.privateCode=link.get('appointment');this.state.managementToken=link.get('key');root.history.replaceState(null,'',root.location.pathname+root.location.search);await this.openAgendaModal({},true);}
    }
    async api(action,data){
      const t=this.storefront.tenant||root.QX_TENANT||{};
      const url=new URL('api/concierge_agenda.php',root.location.href);url.searchParams.set('tenant',t.emisorId||'');url.searchParams.set('action',action);
      const opts={headers:{'Accept':'application/json'}};
      if(data){opts.method='POST';opts.headers['Content-Type']='application/json';opts.body=JSON.stringify(data);}else if(action==='availability')url.searchParams.set('date',this.el('qb_date').value);
      const response=await fetch(url,opts);
      if(action==='generate_ics_calendar'&&response.ok)return response.blob();
      const result=await response.json();if(!response.ok||result.Status!=='OK'){const error=new Error(result.Error||'No pudimos completar la solicitud. Reintenta.');error.status=response.status;throw error;}return result;
    }
    error(message,field){this.text('qb_error',message);this.show('qb_error',Boolean(message));if(field){this.el(field).setAttribute('aria-invalid','true');this.el(field).focus();}}
    busy(value){this.state.busy=value;this.el('qb_next').disabled=value;this.el('qb_back').disabled=value;this.el('qb_details').querySelectorAll('input,textarea').forEach(e=>e.disabled=value);this.el('qb_receipt').querySelectorAll('button').forEach(e=>e.disabled=value);this.el('qb_date').disabled=value;this.el('qb_format').disabled=value||this.rescheduling;this.el('qb_requested_time').disabled=value;this.el('qb_slots').querySelectorAll('button').forEach(e=>e.disabled=value);}
    step(n){this.state.step=n;this.error('');this.show('qb_choose',n===1);this.show('qb_details',n===2);this.show('qb_receipt',n===3);this.show('qb_back',n===2||this.rescheduling);['qb_step_one','qb_step_two','qb_step_done'].forEach((id,i)=>{this.el(id).removeAttribute('aria-current');if(i+1===n)this.el(id).setAttribute('aria-current','step');});this.text('qb_next',n===3?'Cerrar':n===1?(this.rescheduling?'Guardar cambio':'Continuar ↗'):(this.settings&&this.settings.confirmation==='automatic'?'Confirmar cita':'Solicitar cita'));this.text('qb_footer_note',n===3?'Tu cita queda registrada con la tienda.':n===2?'Revisa el resumen antes de enviar.':'Elegir un horario todavía no crea una cita.');this.summary();if(n===2)this.el('qb_name').focus();}
    summary(){if(!this.settings)return;const a=this.state.step===3?this.state.appointment:null;this.text('qb_summary_service',a?a.serviceName:this.settings.serviceName);this.text('qb_summary_time',(a?a.scheduledDate:this.el('qb_date').value)+' · '+(a?a.scheduledTime:this.selectedSlot||'Hora por elegir'));this.text('qb_summary_format',formats[a?a.channel:this.el('qb_format').value]||'Por elegir');this.text('qb_summary_duration',(a?a.duration:this.settings.duration)+' minutos');this.text('qb_timezone','Horario de la tienda · '+(a?a.timezone:this.settings.timezone));}
    async loadConfiguration(){
      this.busy(true);this.error('');try{const data=await this.api('configuration');this.settings=data.settings;this.text('qb_brand',data.brandName||'UNA CONVERSACIÓN CONTIGO');this.text('qb_context_title',this.context.title||this.settings.serviceName);this.el('qb_format').replaceChildren();this.settings.formats.forEach(key=>{const o=document.createElement('option');o.value=key;o.textContent=formats[key];this.el('qb_format').append(o);});this.el('qb_date').min=data.today;const max=new Date(data.today+'T12:00:00Z');max.setUTCDate(max.getUTCDate()+this.settings.horizonDays);this.el('qb_date').max=max.toISOString().slice(0,10);if(!this.el('qb_date').value||this.el('qb_date').value<data.today)this.el('qb_date').value=data.today;this.text('qb_availability_note',this.settings.configured?(this.settings.confirmation==='automatic'?'Horarios disponibles. Tu cita se confirma al completar la reserva.':'Horarios disponibles para solicitar. La tienda confirmará tu cita.'):'Elige tu fecha y hora preferidas. La tienda debe confirmar la disponibilidad.');this.show('qb_requested_time_wrap',!this.settings.configured);this.busy(false);await this.loadSlots();return true;}catch(e){this.error(e.message||'No se pudieron cargar los horarios.');this.text('qb_next','Reintentar');this.busy(false);return false;}
    }
    async loadSlots(){if(!this.settings)return;const version=++this.loadVersion;this.el('qb_slots').replaceChildren();this.text('qb_slots_message','');this.summary();if(!this.settings.configured)return;this.el('qb_next').disabled=true;this.text('qb_slots_message','Consultando disponibilidad…');try{const result=await this.api('availability',this.rescheduling?Object.assign(this.credentials(),{scheduledDate:this.el('qb_date').value}):undefined);if(version!==this.loadVersion)return;const slots=result.slots||[];slots.forEach(time=>{const b=document.createElement('button');b.type='button';b.dataset.time=time;b.textContent=time;b.setAttribute('aria-pressed',String(time===this.selectedSlot));this.el('qb_slots').append(b);});if(!slots.includes(this.selectedSlot))this.selectedSlot='';this.text('qb_slots_message',slots.length?'':'No hay horarios disponibles ese día. Prueba otra fecha.');this.summary();}catch(e){if(version===this.loadVersion)this.error(e.message);}finally{if(version===this.loadVersion)this.el('qb_next').disabled=false;}}
    async openAgendaModal(context={},privateLink=false){
      if(this.el('qx_agenda_modal').classList.contains('active'))return;
      if(!this.available()){this.storefront.showToast('La agenda no está disponible en esta tienda.');return;}
      this.focusBefore=document.activeElement;this.overflowBefore=document.body.style.overflow;this.context=context||{};
      this.el('qx_agenda_modal').classList.add('active');this.el('qx_agenda_modal').setAttribute('aria-hidden','false');this.el('qx_agenda_backdrop').classList.add('active');document.body.style.overflow='hidden';document.documentElement.classList.add('qx-booking-open');document.body.classList.add('qx-booking-open');const rgb=getComputedStyle(this.el('qx_agenda_modal')).backgroundColor.match(/\d+/g);this.el('qx_agenda_modal').style.setProperty('--qb-color-scheme',rgb&&(+rgb[0]*.299 + +rgb[1]*.587 + +rgb[2]*.114)<128?'dark':'light');
      this.inertBefore=Array.from(document.body.children).filter(e=>!['qx_agenda_modal','qx_agenda_backdrop'].includes(e.id)).map(e=>[e,e.inert]);this.inertBefore.forEach(([e])=>{e.inert=true;});this.el('qx_agenda_close').focus();
      this.show('qb_context_image',Boolean(context.image));if(context.image)this.el('qb_context_image').src=context.image;
      this.text('qb_context_title',context.title||'Atención personal');this.text('qx_booking_title',context.title?'Conversemos sobre este espacio.':'Hagamos espacio para tu cita.');
      if(this.state.appointment&&!privateLink){this.receipt(this.state.appointment);return;}
      this.step(1);if(!await this.loadConfiguration())return;
      if(privateLink)await this.refresh();
    }
    closeAgendaModal(){this.el('qx_agenda_modal').classList.remove('active');this.el('qx_agenda_modal').setAttribute('aria-hidden','true');this.el('qx_agenda_backdrop').classList.remove('active');document.body.style.overflow=this.overflowBefore||'';document.documentElement.classList.remove('qx-booking-open');document.body.classList.remove('qx-booking-open');this.inertBefore.forEach(([e,inert])=>{e.inert=inert;});this.inertBefore=[];if(this.focusBefore&&this.focusBefore.isConnected)this.focusBefore.focus();}
    random(){const bytes=new Uint8Array(32);root.crypto.getRandomValues(bytes);return Array.from(bytes,x=>x.toString(16).padStart(2,'0')).join('');}
    async next(){
      if(this.state.busy)return;if(!this.settings){if(await this.loadConfiguration()&&this.privateCode)await this.refresh();return;}if(this.state.step===3){this.closeAgendaModal();return;}
      if(this.state.step===1){if(!this.el('qb_date').value||!this.selectedSlot){this.error('Selecciona la fecha y la hora de tu cita.');return;}if(!this.el('qb_date').checkValidity()){this.error('Selecciona una fecha dentro del período disponible.','qb_date');return;}if(this.rescheduling){await this.privateAction('reschedule',{scheduledDate:this.el('qb_date').value,scheduledTime:this.selectedSlot});return;}this.step(2);return;}
      const payload={clientName:this.el('qb_name').value.trim(),clientEmail:this.el('qb_email').value.trim(),clientPhone:this.el('qb_phone').value.trim(),clientNotes:this.el('qb_notes').value.trim(),scheduledDate:this.el('qb_date').value,scheduledTime:this.selectedSlot,channel:this.el('qb_format').value,productId:this.context.productId||''};
      const invalid=contactError(payload);if(invalid){this.error(invalid[1],invalid[0]);return;}
      const request=this.state.begin(payload,()=>this.random());if(!request)return;this.busy(true);this.error('');this.text('qb_next','Registrando…');
      try{const data=await this.api('submit_appointment_request',request);this.state.finish(data.appointment);this.receipt(data.appointment);}catch(e){this.state.finish();this.error(e.message||'No pudimos comprobar el resultado. Reintenta con los mismos datos para evitar duplicados.');if(e.status===409){this.step(1);this.error(e.message);await this.loadSlots();}else this.text('qb_next','Reintentar solicitud');}finally{this.busy(false);}
    }
    receipt(a){const staleLink=this.el('qb_private_link');if(staleLink)staleLink.remove();this.state.appointment=a;this.privateCode=a.code;this.rescheduling=false;this.step(3);this.show('qb_cancel_confirm',false);this.text('qb_context_title',a.contextTitle||a.serviceName);const confirmed=a.status==='CONFIRMED';this.text('qb_receipt_status',({PENDING:'PENDIENTE DE CONFIRMACIÓN',CONFIRMED:'CITA CONFIRMADA',CANCELLED:'CITA CANCELADA',COMPLETED:'CITA CONCLUIDA',IN_PROGRESS:'CITA EN CURSO',RESCHEDULED:'HORARIO POR CONFIRMAR'})[a.status]||a.status);this.text('qb_receipt_title',a.status==='CANCELLED'?'Tu cita fue cancelada.':a.status==='COMPLETED'?'Gracias por compartir este momento.':a.status==='IN_PROGRESS'?'Tu cita está en curso.':confirmed?'Tu cita está confirmada, '+a.clientName+'.':'Tu solicitud está registrada, '+a.clientName+'.');this.text('qb_receipt_message',a.status==='PENDING'?'La tienda revisará tu solicitud y confirmará la atención. Conserva este enlace para consultar el estado.':confirmed?'Te esperamos en la fecha y hora indicadas.':'Consulta aquí los detalles de tu cita.');const dl=this.el('qb_receipt_details');dl.replaceChildren();[['Correo',a.clientEmail],['Teléfono',a.clientPhone],['Referencia',a.code],['Punto de encuentro',a.location||'La tienda confirmará los detalles de atención.'],['Indicaciones',a.instructions]].forEach(([label,value])=>{if(!value)return;const div=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;div.append(dt,dd);dl.append(div);});const canChange=['PENDING','CONFIRMED','RESCHEDULED'].includes(a.status);this.show('qb_reschedule',canChange);this.show('qb_cancel',canChange);const meeting=this.el('qb_meeting');meeting.hidden=!(a.meetingUrl&&/^https:\/\//i.test(a.meetingUrl));if(!meeting.hidden)meeting.href=a.meetingUrl;this.text('qb_action_status','');}
    credentials(){return {code:this.privateCode||this.state.appointment.code,managementToken:this.state.managementToken};}
    async refresh(){if(this.state.busy)return;this.busy(true);try{const result=await this.api('get_appointment_status',this.credentials());this.receipt(result.appointment);}catch(e){this.error(e.message);}finally{this.busy(false);}}
    async startReschedule(){this.rescheduling=true;this.settings.duration=this.state.appointment.duration;this.step(1);this.el('qb_date').value=this.state.appointment.scheduledDate;this.selectedSlot='';this.el('qb_requested_time').value='';this.el('qb_format').value=this.state.appointment.channel;this.el('qb_format').disabled=true;await this.loadSlots();}
    async privateAction(action,extra={}){if(this.state.busy)return;this.busy(true);try{const result=await this.api(action,Object.assign(this.credentials(),extra));this.receipt(result.appointment);}catch(e){this.error(e.message);if(e.status===409&&this.rescheduling)await this.loadSlots();}finally{this.busy(false);}}
    async copyLink(){const url=new URL(root.location.href);url.searchParams.delete('preview_mode');url.searchParams.delete('t');url.hash=new URLSearchParams({appointment:this.privateCode,key:this.state.managementToken}).toString();try{await navigator.clipboard.writeText(url.href);this.text('qb_action_status','Enlace privado copiado. Guárdalo; permite gestionar tu cita.');}catch(e){this.text('qb_action_status','No se pudo copiar automáticamente.');let input=this.el('qb_private_link');if(!input){input=document.createElement('input');input.id='qb_private_link';input.readOnly=true;input.setAttribute('aria-label','Enlace privado de la cita');this.el('qb_receipt').append(input);}input.value=url.href;input.focus();input.select();}}
    async calendar(){if(this.state.busy)return;this.busy(true);try{const blob=await this.api('generate_ics_calendar',this.credentials());const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Cita-'+this.privateCode+'.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){this.error(e.message);}finally{this.busy(false);}}
  }
  root.QuantixBookingUI=QuantixBookingUI;
})(typeof window==='undefined'?globalThis:window);
