<?php /* Storefront booking dialog; all tenant and visitor content is bound as text. */ ?>
<div class="qx-agenda-backdrop" id="qx_agenda_backdrop"></div>
<section class="qx-agenda-modal qx-booking" id="qx_agenda_modal" role="dialog" aria-modal="true" aria-labelledby="qx_booking_title" aria-hidden="true">
  <header class="qb-header"><div><span class="qb-eyebrow" id="qb_brand">UNA CONVERSACIÓN CONTIGO</span><h2 id="qx_booking_title">Hagamos espacio para tu cita.</h2></div><button type="button" id="qx_agenda_close" class="qb-close" aria-label="Cerrar agenda">×</button></header>
  <div class="qb-progress" aria-label="Progreso de la cita"><span id="qb_step_one" aria-current="step">01 <b>Tu cita</b></span><span id="qb_step_two">02 <b>Tus datos</b></span><span id="qb_step_done">✓ <b>Tu solicitud</b></span></div>
  <div class="qb-alert" id="qb_error" role="alert" hidden></div>
  <div class="qb-layout">
    <aside class="qb-summary"><img id="qb_context_image" alt="" hidden><span class="qb-eyebrow">NOS PREPARAMOS PARA RECIBIRTE</span><h3 id="qb_context_title">Atención personal</h3><p id="qb_context_description">Elige el momento. Cuéntanos cómo podemos ayudarte.</p><dl><div><dt>Servicio</dt><dd id="qb_summary_service">—</dd></div><div><dt>Fecha y hora</dt><dd id="qb_summary_time">Por elegir</dd></div><div><dt>Modalidad</dt><dd id="qb_summary_format">Por elegir</dd></div><div><dt>Duración</dt><dd id="qb_summary_duration">—</dd></div></dl><p class="qb-timezone" id="qb_timezone"></p></aside>
    <div class="qb-main">
      <div id="qb_choose"><h3>Un momento que te venga bien.</h3><p class="qb-hint" id="qb_availability_note">Consultando los horarios de la tienda…</p><label for="qb_format">¿Cómo nos encontramos?</label><select id="qb_format"></select><div class="qb-date-grid"><div><label for="qb_date">Fecha</label><input type="date" id="qb_date" required></div><div id="qb_requested_time_wrap" hidden><label for="qb_requested_time">Hora que prefieres</label><input type="time" id="qb_requested_time" required></div></div><div class="qb-slots" id="qb_slots" role="group" aria-label="Horarios disponibles"></div><p class="qb-hint" id="qb_slots_message" role="status"></p></div>
      <form id="qb_details" hidden novalidate><h3>¿A nombre de quién?</h3><p class="qb-hint">Los tres datos son necesarios para organizar tu cita. No necesitas crear una cuenta.</p><label for="qb_name">Nombre completo <span aria-hidden="true">*</span></label><input id="qb_name" name="name" autocomplete="name" maxlength="128" required placeholder="Tu nombre y apellido"><label for="qb_email">Correo electrónico <span aria-hidden="true">*</span></label><input id="qb_email" name="email" type="email" autocomplete="email" maxlength="128" required placeholder="tu@correo.com"><label for="qb_phone">Teléfono con código de país <span aria-hidden="true">*</span></label><input id="qb_phone" name="tel" type="tel" autocomplete="tel" maxlength="32" required placeholder="+52 55 1234 5678" aria-describedby="qb_phone_hint"><small id="qb_phone_hint">Incluye + y el código de tu país.</small><label for="qb_notes">¿Qué te gustaría que preparemos? <small>Opcional</small></label><textarea id="qb_notes" maxlength="2000" rows="3" placeholder="Lo que te gustaría conocer o resolver en la cita"></textarea><p class="qb-hint">La tienda usará estos datos para atender tu solicitud.</p></form>
      <div id="qb_receipt" hidden><span class="qb-receipt-mark" aria-hidden="true">✓</span><p class="qb-eyebrow" id="qb_receipt_status"></p><h3 id="qb_receipt_title"></h3><p id="qb_receipt_message"></p><dl class="qb-receipt-details" id="qb_receipt_details"></dl><p class="qb-hint">No se ha enviado un correo ni WhatsApp automático. Guarda tu enlace privado para consultar la cita, reprogramarla o cancelarla.</p><a id="qb_meeting" target="_blank" rel="noopener noreferrer" hidden>Abrir videollamada ↗</a><div class="qb-receipt-actions"><button type="button" id="qb_copy_link">Copiar enlace privado</button><button type="button" id="qb_calendar">Agregar a mi calendario</button><button type="button" id="qb_new">Agendar otra cita</button><button type="button" id="qb_refresh">Actualizar estado</button><button type="button" id="qb_reschedule">Reprogramar</button><button type="button" id="qb_cancel">Cancelar cita</button></div><div class="qb-cancel-confirm" id="qb_cancel_confirm" hidden><p>¿Cancelar esta cita? El horario quedará libre.</p><button type="button" id="qb_cancel_yes">Sí, cancelar mi cita</button><button type="button" id="qb_cancel_no">Conservar cita</button></div><p id="qb_action_status" role="status"></p></div>
    </div>
  </div>
  <footer class="qb-footer"><button type="button" id="qb_back" class="qb-secondary" hidden>← Volver</button><p id="qb_footer_note">Elegir un horario todavía no crea una cita.</p><button type="button" id="qb_next" class="qb-primary">Continuar <span aria-hidden="true">↗</span></button></footer>
</section>
